### ISSUE TITLE
VimuxOpenRunner() breaks my tmux pane navigation

### ISSUE THREAD

**Issue by Morantron** [preservim/vimux#124]
I have this mappings in my tmux.conf to navigate tmux panes in and out of vim using <C-hjkl>. But after running `:call VimuxOpenRunner()` these shortcuts stop working.

I have this `g:VimuxUseNearest` set to true.

```
# vim-tmux-navigation
bind -n C-h run "(tmux display-message -p '#{pane_current_command}' | grep -iqE '(^|\/)vim(diff)?$' && tmux send-keys C-h) || tmux select-pane -L"
bind -n C-j run "(tmux display-message -p '#{pane_current_command}' | grep -iqE '(^|\/)vim(diff)?$' && tmux send-keys C-j) || tmux select-pane -D"
bind -n C-k run "(tmux display-message -p '#{pane_current_command}' | grep -iqE '(^|\/)vim(diff)?$' && tmux send-keys C-k) || tmux select-pane -U"
bind -n C-l run "(tmux display-message -p '#{pane_current_command}' | grep -iqE '(^|\/)vim(diff)?$' && tmux send-keys C-l) || tmux select-pane -R"
bind -n C-\ run "(tmux display-message -p '#{pane_current_command}' | grep -iqE '(^|\/)vim(diff)?$' && tmux send-keys 'C-\\') || tmux select-pane -l"
```

Any idea how can I fix this or why it is failing?

Thanks!

**Comment by jgrau** [comment]
I am using https://github.com/christoomey/vim-tmux-navigator and experience the same issue.

**Comment by alerque** [comment]
I use similar navigation bindings and have never had an issue. If this is still a problem for you with an updated plugin and current Tmux version please feel free to comment back here and we'll look into it further. Until I hear otherwise my best guess is that this is a non-issue.

**Comment by Morantron** [comment]
Yep, definitely a non-issue!
