### ISSUE TITLE
VimuxRunCommand Don't Work No More

### ISSUE THREAD

**Issue by yarko3** [preservim/vimux#185]
The following is outputted with any command I give `:VimuxRunCommand`

```
E15: Invalid expression: )
E116: Invalid arguments for function VimuxRunCommand
```

I've pinned the plugin to 57bbdc447877c1bebeff2479aeab9442658e451b and it works fine there so I think this is a recent breakage.

**Comment by alerque** [comment]
I'm sorry you're having trouble with recent changes. However I'm not sure yet what the trouble is. I'm using the latest HEAD version (currently 9214bf9) and am not seeing such an error.

What flavor and version of Vim are you using?

**Comment by yarko3** [comment]
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 12 2020 10:29:41)
Included patches: 1-2269
Modified by team+vim@tracker.debian.org
Compiled by team+vim@tracker.debian.org
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               -farsi             -mouse_sysmouse    -tag_any_white
+arabic            +file_in_path      +mouse_urxvt       +tcl
+autocmd           +find_in_path      +mouse_xterm       +termguicolors
+autochdir         +float             +multi_byte        +terminal
-autoservername    +folding           +multi_lang        +terminfo
+balloon_eval      -footer            -mzscheme          +termresponse
+balloon_eval_term +fork()            +netbeans_intg     +textobjects
+browse            +gettext           +num64             +textprop
++builtin_terms    -hangul_input      +packages          +timers
+byte_offset       +iconv             +path_extra        +title
+channel           +insert_expand     +perl              +toolbar
+cindent           +job               +persistent_undo   +user_commands
+clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +virtualedit
+cmdline_hist      +langmap           -python            +visual
+cmdline_info      +libcall           +python3           +visualextra
+comments          +linebreak         +quickfix          +viminfo
+conceal           +lispindent        +reltime           +vreplace
+cryptv            +listcmds          +rightleft         +wildignore
+cscope            +localmap          +ruby              +wildmenu
+cursorbind        +lua               +scrollbind        +windows
+cursorshape       +menu              +signs             +writebackup
+dialog_con_gui    +mksession         +smartindent       +X11
+diff              +modify_fname      +sound             -xfontset
+digraphs          +mouse             +spell             +xim
+dnd               +mouseshape        +startuptime       +xpm
-ebcdic            +mouse_dec         +statusline        +xsmp_interact
+emacs_tags        +mouse_gpm         -sun_workshop      +xterm_clipboard
+eval              -mouse_jsbterm     +syntax            -xterm_save
+ex_extra          +mouse_netterm     +tag_binary
+extra_search      +mouse_sgr         -tag_old_static
```

**Comment by alerque** [comment]
Hmm. I'm using NeoVIM most of the time myself, but I just checked on my system's VIM which seems to be 8.2. Everything seems fine. Can you try this to isolate just this plugin and test a simple command? Run from a shell (inside TMUX of course!) at the root of this plugin project's directory:

```console
$ vim -i NONE "+set rtp+=$(pwd)" "+so plugin/vimux.vim" "+VimuxRunCommand('date')" "+qa"
```

This should split your window and leave you back at the shell prompt, but with a new pane still open having just run `date`.

**Comment by yarko3** [comment]
Thanks for the hint; I think I see my problem: I was placing my commands in double quotes. Double quotes still error with a minimal vimrc but single quotes work fine.

**Comment by alerque** [comment]
Hmm. Well there you are, I can now replicate your error by using double quotes to quote the command. This means there is an escaping bug somewhere, we'll work on that!

I typically do it the other way because single and double quotes have different meanings in Vimscript, and 99% of the time people *intend* the effects of a single quoted string and are often surprised when their regular expressions do weird things. This is contrary to many languages in which double quotes often are what people expect to use most. In VimL you rarely want to use them.

That still doesn't mean they shouldn't work here. One legitimate use case for them is when you want to include the opposite kind of quote in your string. Again since double quotes are more common in shell languages, single quoting the string in the Vimux command makes more sense, but we'll still look into a fix.

**Comment by yarko3** [comment]
I was able to update my mappings to single quotes so I'm content. Feel free to close out as you see fit.

**Comment by alerque** [comment]
This appears to be a complication arising from #76. Which was fixing something else, so ...

**Comment by alerque** [comment]
I take that back, the actual culprit seems to be a2ab888, which enabled chaining Vimux commands.
