### ISSUE TITLE
VimuxRunnerName doesn't find existing session when runner type is "pane"

### ISSUE THREAD

**Issue by callumacrae** [preservim/vimux#219]
Here's an excerpt from my config:

```
let g:VimuxRunnerType = "pane"
let g:VimuxRunnerName = "vimuxout"
```

Whenever I restart vim, vimux opens a new pane for itself.

I believe this to be a difference in how tmux handles window name and pane names.

This works:

```sh
tmux rename-window vimuxout
tmux select-window -t vimuxout
```

This does not:

```sh
tmux select-pane -T vimuxout
tmux select-pane -t vimuxout
```

Results in "can't find pane: vimuxout" - only `tmux select-pane -t 0` works. It looks like this is because you can't actually rename a pane, you can just set a title, and `select-pane -t` doesn't query the title?

Not really sure. Still trying to figure it out for myself but I've been trying for a while and not having much luck :(

**Comment by callumacrae** [comment]
duh, was missing `let g:VimuxUseNearest = v:true` - which did not do what i thought it does from the name 😅

**Comment by mvanderkamp** [comment]
For more advanced layouts, there's also `g:VimuxRunnerQuery`
