### ISSUE TITLE
VimuxOpenRunner doesn't work any more

### ISSUE THREAD

**Issue by matawed** [preservim/vimux#225]
It seems that my nvim/vimux setup is broken with https://github.com/preservim/vimux/pull/217. If I run `VimuxOpenRunner` it silently fails, meaning that no terminal is opened.

Once I revert this change locally, my setup works again, meaning that terminal is opened as expected.

Tmux version 3.0a/ Ubuntu 20.04

**Comment by matawed** [comment]
Will provide more details upon request/once I have more time to check details.

**Comment by matawed** [comment]
Though `-l size` seems to be supported 

![image](https://github.com/preservim/vimux/assets/30142056/18b33443-9e1f-4efb-9771-1322b74825f4)

**Comment by matawed** [comment]
Naive approach for fixing this issue is to check the exit code of this command and if it fails then issue the other command. I guess, it would be helpful in any case to check exit code and not only silently fail in this case. What do you think?

**Comment by mvanderkamp** [comment]
Ahh, thank you. I think I'll put a conditional in there based on the tmux version.

**Comment by mvanderkamp** [comment]
You know what... should we just say that it's up to the user to decide whether to include the percent sign? This will be a bit of a hiccup when the plugin is updated, since setting `let g:VimuxHeight = "20"` will have to change to `let g:VimuxHeight = "20%"`.

**Comment by jmriego** [comment]
hi! is this change going to be merged? I just found this same issue with tmux 3

**Comment by alerque** [comment]
> is this change going to be merged?

Which change? This is not a PR and I don't see any PRs related to this issue. Contributions welcome. I am not actively developing this plugin but this @preservim org exists to facilitate contributions getting applied so plugins stay maintained as long as contributions flow in. Feel free to jump in.

**Comment by jmriego** [comment]
I don't see any PR either. I was basically asking if anyone was working on this. I'm happy to do a PR. I'll send it this weekend

**Comment by mvanderkamp** [comment]
Yeah sorry, I got distracted by the CI issues on this repo and forgot about this. It would be great to see a PR! We do now check for errors in system calls as of #222 so that could be helpful here.

**Comment by jmriego** [comment]
no worries! just sent a PR. English is not my first language so I'm not sure if the update to the docs sounds natural

**Comment by mvanderkamp** [comment]
Thank you! This does mildly break the config for users who have a custom value for the height option, but the fix is easy and this keeps things simpler going forward.
