### ISSUE TITLE
Can't Get Vimux To Work

### ISSUE THREAD

**Issue by drewrockshard** [preservim/vimux#24]
I'm unable to get Vimux to work.  I'm currently using Pathogen.  I've installed both ways:
- git clone `repo` into `~/.vim/bundles/`
- Downloading the tarball and moving it into `~/.vim/bundles/`

Either way I get the following error:

`E117: Unknown function: RunVimTmuxCommand`

**Comment by aruzmeister** [comment]
I have installed vimux using vundle but it's not working. When i try execute the command
```:help vimux```
it says ```Sorry, no help for Vimux```
