### ISSUE TITLE
Pin vimux to a pane

### ISSUE THREAD

**Issue by pgr0ss** [preservim/vimux#73]
It would be nice if vimux remembered the pane it used last time and used it again. 

Here's my use case:

I am running tests in vimux over and over (vim on top, tests on bottom of tmux split). Every once in awhile, I start a test run and then switch tmux windows to look at something else. If I switch too quickly, vimux now runs the tests in the current window I'm looking at, rather than the pane it was using for tests before.

**Comment by darrinholst** [comment]
@yunake your fork worked for me

**Comment by rbhanot4739** [comment]
I think this is a needed feature not sure why it hasn't been merged yet.

**Comment by alerque** [comment]
PR #110 merged the referenced fork into the canonical repository. This should be fixed for everybody now.
