### ISSUE TITLE
The master doesn't work with 1.6

### ISSUE THREAD

**Issue by yevgenko** [preservim/vimux#78]
Ubuntu 12.04
tmux 1.6 - from official sources
vmux master branch

Expected pane created, but getting endless prompt in vim

Upgrading tmux to 1.8 solved issue

**Comment by alerque** [comment]
I'm completely uninterested in tracking this down. I'm running Tmux 3.1c. I don't know what our current minimum supported version even is, but if updating to some release that was newly available 8 years ago resolved this, I think we can call this a non-issue.
