### ISSUE TITLE
VimuxSendText() escaping

### ISSUE THREAD

**Issue by smondet** [preservim/vimux#87]
I was having trouble with `VimuxSendText` when the text contained `'$'` characters.

The function only escapes `'"'`, c.f https://github.com/benmills/vimux/blob/master/plugin/vimux.vim#L45

I was luckier with

```
call VimuxSendKeys("'" . escape(@k, "'") . "'")
```

i.e. call `system` with single quotes and only escape those.

Maybe it can be usefull for others (?).

Cheers

**Comment by alerque** [comment]
This should be addressed by 46377b8. Feel free to comment if this doesn't cover all the possible escaping issues, but I think it will.
