### ISSUE TITLE
Double semi-colons not escaped correctly

### ISSUE THREAD

**Issue by libanp** [preservim/vimux#88]
I'm trying to use vimux with OCaml, so I make heavy use of double semi-colons (;;) at the end of lines.

Initially one of the semi-colons would get dropped. I edited 

```
call VimuxSendKeys('"'.escape(a:text, '"').'"')
```

To

```
call VimuxSendKeys('"'.escape(a:text, '";`').'"')
```

However now ;; comes out as \;;

So I'm stuck getting either a single ; or \;; which OCaml won't accept.

**Comment by alerque** [comment]
This should be resolved in 46377b8.
